services:
  entity-client:
    build:
      context: ../
      dockerfile: deploy/docker/entity-client/Dockerfile
      args:
        NEXT_PUBLIC_EC_API_BASE_URL: ${NEXT_PUBLIC_EC_API_BASE_URL}
        NEXT_PUBLIC_EC_DEFAULT_JWT: ${NEXT_PUBLIC_EC_DEFAULT_JWT}
        NEXT_PUBLIC_RAG_DOCK_SCRIPT_URL: ${NEXT_PUBLIC_RAG_DOCK_SCRIPT_URL}
        NEXT_PUBLIC_HOST_APP_ID: ${NEXT_PUBLIC_HOST_APP_ID}
        NEXT_PUBLIC_HOST_DENSITY: ${NEXT_PUBLIC_HOST_DENSITY}
        NEXT_PUBLIC_EMBED_LOCK_ENABLED: ${NEXT_PUBLIC_EMBED_LOCK_ENABLED}
    restart: unless-stopped
    env_file:
      - ./env/entity-client.env
      - /opt/stacks/portfolio/deploy/shared/env/embed.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "127.0.0.1:3005:3005"

    init: true