services:
  entity-client:
    build:
      context: ../
      dockerfile: deploy/docker/entity-client/Dockerfile

    restart: unless-stopped
    env_file:
      - ./env/entity-client.env
      - /opt/stacks/portfolio/deploy/shared/env/embed.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "127.0.0.1:3005:3005"

    init: true